### ISSUE TITLE
Bug: Message count error in DMs

### ISSUE THREAD

**Issue by sebastiaan-daniels** [Arborym/Pax-Academia#174]
Every time a user sends a direct message to the bot (not a command), the bot raises an error in messagecounter.py

```
Traceback (most recent call last):
  File "xxx\client.py", line 378, in _run_event
    await coro(*args, **kwargs)
  File "xxx\MessageCounter.py", line 31, in on_message
    category_name = message.channel.category.name.lower()
                    ^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'DMChannel' object has no attribute 'category'
```

Fix: exit (return) event (on_message) if message is a direct message

**Comment by Arborym** [comment]
Would this just be:
```py
if message.guild is None:
	return
```
?
